### PR TITLE
Change spoof to use circle to search

### PR DESCRIPTION
**Pull request by HotarunIchijou**
Changed spoof for ability to use circle to search (right now it seems that cicrcle to search doesn't really work with pixelify, it opens by long press but at least for me nothing can be circled)

Actually there's no need for so much strings, it can work in the following way:
ro.product.brand=google
ro.product.device=husky
ro.product.manufacturer=Google
ro.product.model=Pixel 8
ro.product.name=husky

### CODE REVIEW

**Comment by Fede2782** [comment]
Maybe it not even needed. On Samsung (for example) devices with One UI 6.1 you can enable Circle2Search by just these two props

```
ro.com.google.cdb.spa1=bsxasm1
ro.bbt.support.circle2search=true
``` 

And with this feature flag in sysconfig

```
com.samsung.feature.EXPERIENCE_CTS
```

**Comment by Kingsman44** [comment]
> Changed spoof for ability to use circle to search (right now it seems that cicrcle to search doesn't really work with pixelify, it opens by long press but at least for me nothing can be circled)
> 
> Actually there's no need for so much strings, it can work in the following way: ro.product.brand=google ro.product.device=husky ro.product.manufacturer=Google ro.product.model=Pixel 8 ro.product.name=husky

Pixelify doesn't use spoof.prop, spoofing is managed by Zygisk Library.

**Comment by Kingsman44** [comment]
Changing it won't help for Circle2Search. Hence I am closing this pull request. And Don't worry it will be there on next version of Pixelify.

**Comment by HotarunIchijou** [comment]
> Changing it won't help for Circle2Search
then why after that I got working circle to search?

**Comment by HotarunIchijou** [comment]
I was wrong. It happened randomly when I used some flags and this spoof

**Comment by Fede2782** [comment]
> I was wrong. It happened randomly when I applied some flags and this spoof

Which flags did you enable? Could you tell me how you enabled Circle2Search if you did in a working way?

**Comment by HotarunIchijou** [comment]
> Could you tell me how you enabled Circle2Search if you did in a working way?

First, you need to enable some flags through adb:
`adb shell cmd device_config put launcher long_press_home_button_to_search true;adb shell cmd device_config put launcher long_press_home_button_to_search_mpr true;adb shell cmd device_config put launcher press_hold_nav_handle_to_search true;adb shell cmd device_config put launcher press_hold_nav_handle_to_search_mpr true;adb shell cmd device_config put launcher ENABLE_SETTINGS_OSE_CUSTOMIZATIONS true;adb shell cmd device_config put launcher ENABLE_LONG_PRESS_NAV_HANDLE true;adb shell cmd device_config put launcher ENABLE_LONG_PRESS_NAV_HANDLE_MPR true;adb shell cmd device_config put launcher INVOKE_OMNI_LPH true;adb shell cmd device_config put launcher INVOKE_OMNI_LPH_MPR true` 

Or even easier, flash this magisk module: https://github.com/fillwithjoy1/circle-to-search

After that, you need to spoof your device in any way (pixelify will be enough ig)
If you got stucked screen after that (aka can't circle in circle to search), install this version of Google app through SAI: https://www.apkmirror.com/apk/google-inc/google-search/google-search-15-6-38-release/google-app-15-6-38-29-arm64-android-apk-download/download/?key=74317348958251decb626fdc10dfd76b70cb7619

After you install that, circle to search should work and you can update Google app to the latest version

**Comment by Fede2782** [comment]
> > Could you tell me how you enabled Circle2Search if you did in a working way?
> 
> First, you need to enable some flags through adb: `adb shell cmd device_config put launcher long_press_home_button_to_search true;adb shell cmd device_config put launcher long_press_home_button_to_search_mpr true;adb shell cmd device_config put launcher press_hold_nav_handle_to_search true;adb shell cmd device_config put launcher press_hold_nav_handle_to_search_mpr true;adb shell cmd device_config put launcher ENABLE_SETTINGS_OSE_CUSTOMIZATIONS true;adb shell cmd device_config put launcher ENABLE_LONG_PRESS_NAV_HANDLE true;adb shell cmd device_config put launcher ENABLE_LONG_PRESS_NAV_HANDLE_MPR true;adb shell cmd device_config put launcher INVOKE_OMNI_LPH true;adb shell cmd device_config put launcher INVOKE_OMNI_LPH_MPR true`
> 
> Or even easier, flash this magisk module: https://github.com/fillwithjoy1/circle-to-search
> 
> After that, you need to spoof your device in any way (pixelify will be enough ig) If you got stucked screen after that (aka can't circle in circle to search), install this version of Google app through SAI: https://www.apkmirror.com/apk/google-inc/google-search/google-search-15-6-38-release/google-app-15-6-38-29-arm64-android-apk-download/download/?key=74317348958251decb626fdc10dfd76b70cb7619
> 
> After you install that, circle to search should work and you can update Google app to the latest version
> 
> Note: you won't get translate button in circle to search

I do not have a pixel/aosp device so i don't think they will work

**Pull request closed without merging**
